<a href="https://colab.research.google.com/github/hnidey13/tesis_SVD_t-SVDM/blob/main/ejemplo_cambio_de_dominio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Limpiamos área de trabajo

In [1]:
rm(list=ls())

Obtener $\widehat{\boldsymbol{\mathcal{A}}}$ a partir de $\boldsymbol{\mathcal{A}}$

Tensor $\boldsymbol{\mathcal{A}}\in\mathbb{R}^{2\times2\times2}$


In [3]:
A <- array(c(1,0,2,-1,
             -1,1,1,1),
           c(2,2,2))
print(A)

, , 1

     [,1] [,2]
[1,]    1    2
[2,]    0   -1

, , 2

     [,1] [,2]
[1,]   -1    1
[2,]    1    1



Matriz $M\in\mathbb{R}^{2\times2}$

In [9]:
M <- matrix(c(3,1,2,1),2,2)
M

[,1] [,2]
[1,] 3    2   
[2,] 1    1

Desdoble de forma $3$ de $\boldsymbol{\mathcal{A}}$

In [10]:
A3 <- cbind(A[1,1,],A[1,2,],A[2,1,],A[2,2,])
A3

[,1] [,2] [,3] [,4]
[1,]  1   2    0    -1  
[2,] -1   1    1     1

Producto $\boldsymbol{M}\boldsymbol{\mathcal{A}}_{(3)}$

In [11]:
M_x_A3 <- M %*% A3
M_x_A3

[,1] [,2] [,3] [,4]
[1,] 1    8    2    -1  
[2,] 0    3    1     0

Doblez de forma $3$

In [13]:
A_hat <- array(dim = c(2,2,2))
A_hat[1,1,] <- M_x_A3[,1]
A_hat[1,2,] <- M_x_A3[,2]
A_hat[2,1,] <- M_x_A3[,3]
A_hat[2,2,] <- M_x_A3[,4]
print(A_hat)

, , 1

     [,1] [,2]
[1,]    1    8
[2,]    2   -1

, , 2

     [,1] [,2]
[1,]    0    3
[2,]    1    0



###Proceso inverso (obtener $\boldsymbol{\mathcal{A}}$ a partir de $\widehat{\boldsymbol{\mathcal{A}}}$)

In [15]:
print(A_hat)

, , 1

     [,1] [,2]
[1,]    1    8
[2,]    2   -1

, , 2

     [,1] [,2]
[1,]    0    3
[2,]    1    0



Desdoble de forma $3$

In [16]:
M_x_A3 <- cbind(A_hat[1,1,],A_hat[1,2,],A_hat[2,1,],A_hat[2,2,])
M_x_A3

[,1] [,2] [,3] [,4]
[1,] 1    8    2    -1  
[2,] 0    3    1     0

Multiplicación matricial inversa

In [18]:
A3 <- solve(M) %*% M_x_A3
A3

[,1] [,2] [,3] [,4]
[1,]  1   2    0    -1  
[2,] -1   1    1     1

Doblez de forma $3$ de $\boldsymbol{\mathcal{A}}_{(3)}$

In [20]:
A <- array(dim = c(2,2,2))
A[1,1,] <- A3[,1]
A[1,2,] <- A3[,2]
A[2,1,] <- A3[,3]
A[2,2,] <- A3[,4]
print(A)

, , 1

     [,1] [,2]
[1,]    1    2
[2,]    0   -1

, , 2

     [,1] [,2]
[1,]   -1    1
[2,]    1    1

