<a href="https://colab.research.google.com/github/hnidey13/tesis_SVD_t-SVDM/blob/main/ejemplo_t-SVDM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Limpiamos área de trabajo

In [109]:
rm(list=ls())

Tensor $\boldsymbol{\mathcal{A}}\in\mathbb{R}^{2\times2\times2}$

In [110]:
A <- array(c(1,0,2,-1,
             -1,1,1,1),
           c(2,2,2))
print(A)

, , 1

     [,1] [,2]
[1,]    1    2
[2,]    0   -1

, , 2

     [,1] [,2]
[1,]   -1    1
[2,]    1    1



Matriz $\boldsymbol{M}\in\mathbb{R}^{2\times2}$

In [111]:
M <- matrix(c(3,1,2,1),2,2)
M

[,1] [,2]
[1,] 3    2   
[2,] 1    1

Desdoble de forma $3$ de $\boldsymbol{\mathcal{A}}$

In [112]:
A3 <- cbind(A[1,1,],A[1,2,],A[2,1,],A[2,2,])

Producto $\boldsymbol{M}\boldsymbol{\mathcal{A}}_{(3)}$

In [113]:
M_x_A3 <- M %*% A3

Doblez de forma $3$

In [114]:
A_hat <- array(dim = c(2,2,2))
A_hat[1,1,] <- M_x_A3[,1]
A_hat[1,2,] <- M_x_A3[,2]
A_hat[2,1,] <- M_x_A3[,3]
A_hat[2,2,] <- M_x_A3[,4]
print(A_hat)

, , 1

     [,1] [,2]
[1,]    1    8
[2,]    2   -1

, , 2

     [,1] [,2]
[1,]    0    3
[2,]    1    0



SVD para cada cara

In [115]:
svd1 <- svd(A_hat[,,1])
svd2 <- svd(A_hat[,,2])

Reshape para tensor de orden $p=3$

In [116]:
U_hat <- array(cbind(svd1$u,svd2$u),c(2,2,2))
S_hat <- array(cbind(diag(svd1$d),diag(svd2$d)),c(2,2,2))
V_T_hat <- array(cbind(t(svd1$v),t(svd2$v)),c(2,2,2))

Regresamos el tensor $\widehat{\boldsymbol{\mathcal{U}}}$ al dominio original

In [117]:
M_x_U3 <- cbind(U_hat[1,1,],U_hat[1,2,],U_hat[2,1,],U_hat[2,2,])
U3 <- solve(M) %*% M_x_U3
U <- array(dim = c(2,2,2))
U[1,1,] <- U3[,1]
U[1,2,] <- U3[,2]
U[2,1,] <- U3[,3]
U[2,2,] <- U3[,4]
print(U)

, , 1

           [,1]       [,2]
[1,] 1.00486667 0.09853762
[2,] 0.09853762 2.99513333

, , 2

            [,1]        [,2]
[1,] -2.00486667 -0.09853762
[2,] -0.09853762 -3.99513333



Regresamos el tensor $\widehat{\boldsymbol{\mathcal{S}}}$ al dominio original

In [118]:
M_x_S3 <- cbind(S_hat[1,1,],S_hat[1,2,],S_hat[2,1,],S_hat[2,2,])
S3 <- solve(M) %*% M_x_S3
S <- array(dim = c(2,2,2))
S[1,1,] <- S3[,1]
S[1,2,] <- S3[,2]
S[2,1,] <- S3[,3]
S[2,2,] <- S3[,4]
print(S)

, , 1

        [,1]       [,2]
[1,] 2.09902 0.00000000
[2,] 0.00000 0.09901951

, , 2

          [,1]      [,2]
[1,] 0.9009805 0.0000000
[2,] 0.0000000 0.9009805



Regresamos el tensor $\widehat{\boldsymbol{\mathcal{V}}^T}$ al dominio original

In [119]:
V_T3 <- cbind(V_T_hat[1,1,],V_T_hat[1,2,],V_T_hat[2,1,],V_T_hat[2,2,])
M_x_V_T3 <- solve(M) %*% V_T3
V_T <- array(dim = c(2,2,2))
V_T[1,1,] <- M_x_V_T3[,1]
V_T[1,2,] <- M_x_V_T3[,2]
V_T[2,1,] <- M_x_V_T3[,3]
V_T[2,2,] <- M_x_V_T3[,4]
print(V_T)

, , 1

            [,1]        [,2]
[1,] -0.09853762  1.00486667
[2,]  2.99513333 -0.09853762

, , 2

            [,1]        [,2]
[1,]  0.09853762 -2.00486667
[2,] -3.99513333  0.09853762



###Calculamos el producto $\boldsymbol{\mathcal{U}}\star_M\boldsymbol{\mathcal{S}}\star_M\boldsymbol{\mathcal{V}}^T$

Primero calculemos $\boldsymbol{\mathcal{U}}\star_M\boldsymbol{\mathcal{S}}$

In [120]:
face_prod <- array(
    c(U_hat[,,1] %*% S_hat[,,1],
      U_hat[,,2] %*% S_hat[,,2]), c(2,2,2)
)
print(face_prod)
temp3 <- solve(M) %*% cbind(face_prod[1,1,],face_prod[1,2,],face_prod[2,1,],face_prod[2,2,]) #desdoblando
U_starM_S <- array(dim = c(2,2,2))
U_starM_S[1,1,] <- temp3[,1]
U_starM_S[1,2,] <- temp3[,2]
U_starM_S[2,1,] <- temp3[,3]
U_starM_S[2,2,] <- temp3[,4]
print(U_starM_S)

, , 1

           [,1]      [,2]
[1,] -8.0596042 0.2068324
[2,]  0.7980581 2.0888043

, , 2

     [,1] [,2]
[1,]   -3    0
[2,]    0   -1

, , 1

           [,1]      [,2]
[1,] -2.0596042 0.2068324
[2,]  0.7980581 4.0888043

, , 2

           [,1]       [,2]
[1,] -0.9403958 -0.2068324
[2,] -0.7980581 -5.0888043



Ahora calculamos $\boldsymbol{\mathcal{A}}=\boldsymbol{\mathcal{C}}\star_M\boldsymbol{\mathcal{V}}^T$, donde $\boldsymbol{\mathcal{C}} = \boldsymbol{\mathcal{U}}\star_M\boldsymbol{\mathcal{S}}$

In [121]:
C <- U_starM_S

Primero calculemos $\widehat{\boldsymbol{\mathcal{C}}}$

Desdoble de forma $3$ de $\widehat{\boldsymbol{\mathcal{C}}}$

In [122]:
C3 <- cbind(C[1,1,],C[1,2,],C[2,1,],C[2,2,])

Multiplicamos

In [123]:
M_x_C3 <- M %*% C3

Doblez

In [124]:
C_hat <- array(dim = c(2,2,2))
C_hat[1,1,] <- M_x_C3[,1]
C_hat[1,2,] <- M_x_C3[,2]
C_hat[2,1,] <- M_x_C3[,3]
C_hat[2,2,] <- M_x_C3[,4]
print(C_hat)

, , 1

           [,1]      [,2]
[1,] -8.0596042 0.2068324
[2,]  0.7980581 2.0888043

, , 2

     [,1] [,2]
[1,]   -3    0
[2,]    0   -1



Producto en términos de cara

In [125]:
face_prod <- array(
    c(C_hat[,,1] %*% V_T_hat[,,1],
      C_hat[,,2] %*% V_T_hat[,,2]), c(2,2,2)
)
print(face_prod)

, , 1

     [,1] [,2]
[1,]    1    8
[2,]    2   -1

, , 2

     [,1] [,2]
[1,]    0    3
[2,]    1    0



Regresamos al domino original y doblamos

In [126]:
temp3 <- solve(M) %*% cbind(face_prod[1,1,],face_prod[1,2,],face_prod[2,1,],face_prod[2,2,]) #desdoblando
A_SVD <- array(dim = c(2,2,2))
A_SVD[1,1,] <- temp3[,1]
A_SVD[1,2,] <- temp3[,2]
A_SVD[2,1,] <- temp3[,3]
A_SVD[2,2,] <- temp3[,4]
print(round(A_SVD,4))
print(A)

, , 1

     [,1] [,2]
[1,]    1    2
[2,]    0   -1

, , 2

     [,1] [,2]
[1,]   -1    1
[2,]    1    1

, , 1

     [,1] [,2]
[1,]    1    2
[2,]    0   -1

, , 2

     [,1] [,2]
[1,]   -1    1
[2,]    1    1

