<a href="https://colab.research.google.com/github/hnidey13/tesis_SVD_t-SVDM/blob/main/PCA_propiedades.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Limpiamos área de trabajo

In [1]:
rm(list=ls())

Definimos una normal multivariada de dimensión $p$


In [2]:
library(MASS)
set.seed(1)
p <- 5
(mu <- rnorm(p)) #Vector de medias
(Sigma <- rWishart(1,p,diag(p))[,,1]) #Cov(X)
(corMat <- cov2cor(Sigma)) #Cor(X)

[1] -0.6264538  0.1836433 -0.8356286  1.5952808  0.3295078

[,1]       [,2]       [,3]       [,4]       [,5]      
[1,]  2.0159492  0.8175181 -1.1344663  1.5972233  1.3048020
[2,]  0.8175181  2.6530395 -2.2086845  0.5792511  1.7208336
[3,] -1.1344663 -2.2086845  3.3913867 -0.8666622 -1.5425465
[4,]  1.5972233  0.5792511 -0.8666622  1.9002842 -0.5847361
[5,]  1.3048020  1.7208336 -1.5425465 -0.5847361  7.1877857

[,1]       [,2]       [,3]       [,4]       [,5]      
[1,]  1.0000000  0.3534970 -0.4338735  0.8160496  0.3427735
[2,]  0.3534970  1.0000000 -0.7363311  0.2579798  0.3940664
[3,] -0.4338735 -0.7363311  1.0000000 -0.3413909 -0.3124295
[4,]  0.8160496  0.2579798 -0.3413909  1.0000000 -0.1582170
[5,]  0.3427735  0.3940664 -0.3124295 -0.1582170  1.0000000

Simulamos n observaciones

In [3]:
n <- 100
A <- mvrnorm(n = n, mu, Sigma)
Ac <- scale(A, center = TRUE, scale = FALSE) #Matriz con datos centrados

Estimaciones de mean(X'), cov(X') y cor(X')

In [4]:
colMeans(A)
cov(A)
cor(A)

[1] -0.64576729  0.04283259 -0.71459867  1.68628450  0.07016862

[,1]       [,2]       [,3]      [,4]       [,5]      
[1,]  2.0003007  0.4674296 -1.096025  1.7877000  0.6528109
[2,]  0.4674296  2.2381348 -1.926503  0.5419785  0.9465673
[3,] -1.0960252 -1.9265031  3.254768 -1.0910756 -1.0352595
[4,]  1.7877000  0.5419785 -1.091076  2.2422848 -0.7237453
[5,]  0.6528109  0.9465673 -1.035260 -0.7237453  5.3540710

[,1]       [,2]       [,3]       [,4]       [,5]      
[1,]  1.0000000  0.2209151 -0.4295492  0.8441150  0.1994792
[2,]  0.2209151  1.0000000 -0.7137837  0.2419321  0.2734427
[3,] -0.4295492 -0.7137837  1.0000000 -0.4038773 -0.2479974
[4,]  0.8441150  0.2419321 -0.4038773  1.0000000 -0.2088807
[5,]  0.1994792  0.2734427 -0.2479974 -0.2088807  1.0000000

Estimaciones de mean(X), cov(X) y cor(X)

In [5]:
colMeans(Ac)
(Sigma_X_est <- cov(Ac))
t(Ac)%*%Ac/(n-1)
cor(Ac)

[1]  9.270362e-17 -2.275957e-17  9.436896e-18 -1.021405e-16  5.551115e-18

[,1]       [,2]       [,3]      [,4]       [,5]      
[1,]  2.0003007  0.4674296 -1.096025  1.7877000  0.6528109
[2,]  0.4674296  2.2381348 -1.926503  0.5419785  0.9465673
[3,] -1.0960252 -1.9265031  3.254768 -1.0910756 -1.0352595
[4,]  1.7877000  0.5419785 -1.091076  2.2422848 -0.7237453
[5,]  0.6528109  0.9465673 -1.035260 -0.7237453  5.3540710

[,1]       [,2]       [,3]      [,4]       [,5]      
[1,]  2.0003007  0.4674296 -1.096025  1.7877000  0.6528109
[2,]  0.4674296  2.2381348 -1.926503  0.5419785  0.9465673
[3,] -1.0960252 -1.9265031  3.254768 -1.0910756 -1.0352595
[4,]  1.7877000  0.5419785 -1.091076  2.2422848 -0.7237453
[5,]  0.6528109  0.9465673 -1.035260 -0.7237453  5.3540710

[,1]       [,2]       [,3]       [,4]       [,5]      
[1,]  1.0000000  0.2209151 -0.4295492  0.8441150  0.1994792
[2,]  0.2209151  1.0000000 -0.7137837  0.2419321  0.2734427
[3,] -0.4295492 -0.7137837  1.0000000 -0.4038773 -0.2479974
[4,]  0.8441150  0.2419321 -0.4038773  1.0000000 -0.2088807
[5,]  0.1994792  0.2734427 -0.2479974 -0.2088807  1.0000000

PCA sobre Ac (probabilista)


In [6]:
L <- eigen(Sigma)$vectors
L

[,1]        [,2]       [,3]       [,4]        [,5]       
[1,] -0.26549194 -0.3231776  0.5943204  0.01696472  0.68670642
[2,] -0.38183122 -0.3101252 -0.4225222 -0.75581860  0.09077714
[3,]  0.41269061  0.4737353  0.4359356 -0.64403043  0.02112549
[4,] -0.07457246 -0.5096392  0.4927581 -0.11183558 -0.69237928
[5,] -0.77964374  0.5614458  0.1881696  0.03417675 -0.20089412

PCA sobre Ac (estadístico)

In [7]:
(L_est <- prcomp(Ac)$rotation) #Usa SVD
princomp(Ac)$loadings #Usa eigen (no funciona si p>n)
round(eigen(cov(Ac))$vectors,3) #Equivalentemente

PC1        PC2        PC3        PC4        PC5        
[1,]  0.3132899  0.3224097 -0.5598007 0.02843828  0.69549685
[2,]  0.4044488  0.1487637  0.5074999 0.73521146  0.12727324
[3,] -0.5419837 -0.3132763 -0.4264810 0.65257094  0.01940902
[4,]  0.1937018  0.5519721 -0.4069681 0.18005589 -0.67805842
[5,]  0.6379686 -0.6863717 -0.2855833 0.01965752 -0.19986427


Loadings:
     Comp.1 Comp.2 Comp.3 Comp.4 Comp.5
[1,]  0.313  0.322  0.560         0.695
[2,]  0.404  0.149 -0.507  0.735  0.127
[3,] -0.542 -0.313  0.426  0.653       
[4,]  0.194  0.552  0.407  0.180 -0.678
[5,]  0.638 -0.686  0.286        -0.200

               Comp.1 Comp.2 Comp.3 Comp.4 Comp.5
SS loadings       1.0    1.0    1.0    1.0    1.0
Proportion Var    0.2    0.2    0.2    0.2    0.2
Cumulative Var    0.2    0.4    0.6    0.8    1.0

[,1]   [,2]   [,3]   [,4]   [,5]  
[1,] -0.313 -0.322 -0.560 -0.028  0.695
[2,] -0.404 -0.149  0.507 -0.735  0.127
[3,]  0.542  0.313 -0.426 -0.653  0.019
[4,] -0.194 -0.552 -0.407 -0.180 -0.678
[5,] -0.638  0.686 -0.286 -0.020 -0.200

### Propiedades
1. $\operatorname{Var}[Y_i] = \gamma_i$
2. $\operatorname{Cov}(Y_i,Y_j)=0$


Probabilista

In [8]:
(Sigma_Y <- round(t(L) %*% Sigma %*% L,4))
round(eigen(Sigma)$values,4)

[,1]   [,2]   [,3] [,4]   [,5] 
[1,] 9.2355 0.0000 0.00 0.0000 0.000
[2,] 0.0000 4.7154 0.00 0.0000 0.000
[3,] 0.0000 0.0000 2.34 0.0000 0.000
[4,] 0.0000 0.0000 0.00 0.7606 0.000
[5,] 0.0000 0.0000 0.00 0.0000 0.097

[1] 9.2355 4.7154 2.3400 0.7606 0.0970

Estimación

In [9]:
Y_est <- Ac %*% L_est
#princomp(Ac)$scores #Equivalentemente
(Sigma_Y_est <- round(cov(Y_est),4))

PC1    PC2    PC3    PC4    PC5   
PC1 6.9345 0.0000 0.0000 0.0000 0.0000
PC2 0.0000 4.9518 0.0000 0.0000 0.0000
PC3 0.0000 0.0000 2.3742 0.0000 0.0000
PC4 0.0000 0.0000 0.0000 0.7043 0.0000
PC5 0.0000 0.0000 0.0000 0.0000 0.1248

3. $\sum\operatorname{Var}[X_i]=\sum\operatorname{Var}[Y_i]=\sum\gamma_i$

Probabilista

In [10]:
sum(diag(Sigma))
sum(diag(Sigma_Y))

[1] 17.14845

[1] 17.1485

Estadístico

In [11]:
sum(diag(Sigma_X_est))
sum(diag(Sigma_Y_est))

[1] 15.08956

[1] 15.0896

4. $\mathbb{E}[\Vert X-L(L^TX)\Vert^2]=\sum\gamma_i$

Estadístico

In [12]:
d <- 2
error_fun <- function(X,L) sum((X - L %*% t(L) %*% X)^2)
mean(sapply(1:nrow(Ac), function(i) error_fun(Ac[i,],L[,1:d])))
sum(diag(Sigma_Y_est)[(d+1):p])

[1] 3.237453

[1] 3.2033