<a href="https://colab.research.google.com/github/hnidey13/tesis_SVD_t-SVDM/blob/main/SVD_relaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Limpiamos área de trabajo

In [5]:
rm(list=ls())

##SVD


Matriz $A$

In [6]:
A <- matrix(c(3,1,1,
              -1,3,1),2,3,byrow=TRUE)
A <- matrix(c(4,7,-1,8,-5,-2,4,2,-1,3,-3,6),4,3)
n <- nrow(A)
p <- ncol(A)
A

[,1] [,2] [,3]
[1,]  4   -5   -1  
[2,]  7   -2    3  
[3,] -1    4   -3  
[4,]  8    2    6

Rango de $A$

In [7]:
library(Matrix)
(ranA <- rankMatrix(A))

[1] 3
attr(,"method")
[1] "tolNorm2"
attr(,"useGrad")
[1] FALSE
attr(,"tol")
[1] 8.881784e-16

Matriz $AA^T$

In [8]:
A%*%t(A)

[,1] [,2] [,3] [,4]
[1,]  42   35  -21   16 
[2,]  35   62  -24   70 
[3,] -21  -24   26  -18 
[4,]  16   70  -18  104

Matriz $A^TA$

In [9]:
t(A)%*%A

[,1] [,2] [,3]
[1,] 130  -22  68  
[2,] -22   49  -1  
[3,]  68   -1  55

Eigenvalores de $AA^T$ y $A^TA$

In [10]:
(lambda2 <- eigen(A%*%t(A))$values)
(lambda2 <- eigen(t(A)%*%A)$values)
lambda <- sqrt(lambda2)

[1] 1.732174e+02 4.899849e+01 1.178407e+01 5.130117e-15

[1] 173.21745  48.99849  11.78407

Eigenvectores de $AA^T$ y $A^TA$

In [11]:
#(Es necesario ajustar signos manualmente)
U <- eigen(A%*%t(A))$vectors
V <- eigen(t(A)%*%A)$vectors
V[,1] <- -V[,1]
V[,2] <- -V[,2]

Sigue siendo descomposición espectral

In [12]:
t(A)%*%A
V %*% diag(eigen(t(A)%*%A)$values) %*% t(V)

[,1] [,2] [,3]
[1,] 130  -22  68  
[2,] -22   49  -1  
[3,]  68   -1  55

[,1] [,2] [,3]
[1,] 130  -22  68  
[2,] -22   49  -1  
[3,]  68   -1  55

Formamos matriz $\Lambda$

In [13]:
Lambda <- matrix(0, nrow = n, ncol = p)
diag(Lambda) <- lambda[1:ranA]

Comprobación

In [14]:
U%*%Lambda%*%t(V)
A

[,1] [,2] [,3]
[1,]  4   -5   -1  
[2,]  7   -2    3  
[3,] -1    4   -3  
[4,]  8    2    6

[,1] [,2] [,3]
[1,]  4   -5   -1  
[2,]  7   -2    3  
[3,] -1    4   -3  
[4,]  8    2    6

SVD (reducida)

In [15]:
thinSVD_A <- svd(A)
thinSVD_A$u %*% diag(thinSVD_A$d) %*% t(thinSVD_A$v)

[,1] [,2] [,3]
[1,]  4   -5   -1  
[2,]  7   -2    3  
[3,] -1    4   -3  
[4,]  8    2    6

Comprobación SVD (suma de matrices de rango 1)

In [16]:
MatRan1 <- function(i) (lambda[i] * U[,i] %*% t(V[,i]))
(listMatRan1 <- lapply(1:ranA, MatRan1))
Reduce("+", listMatRan1)


[[1]]
          [,1]       [,2]      [,3]
[1,]  3.172071 -0.5765297  1.829487
[2,]  6.658806 -1.2102502  3.840457
[3,] -2.531539  0.4601118 -1.460061
[4,]  8.125657 -1.4768531  4.686462

[[2]]
            [,1]      [,2]       [,3]
[1,]  0.07485334 -4.837064 -1.6540977
[2,]  0.01499370 -0.968901 -0.3313285
[3,] -0.04141120  2.676015  0.9150984
[4,] -0.05440966  3.515983  1.2023365

[[3]]
            [,1]       [,2]       [,3]
[1,]  0.75307589  0.4135938 -1.1753898
[2,]  0.32620039  0.1791512 -0.5091288
[3,]  1.57294983  0.8638735 -2.4550370
[4,] -0.07124739 -0.0391295  0.1112019

[,1] [,2] [,3]
[1,]  4   -5   -1  
[2,]  7   -2    3  
[3,] -1    4   -3  
[4,]  8    2    6

SVD (completa)

In [17]:
svd_A = svd(A, nu = nrow(A), nv = ncol(A))
svd_A$u
svd_A$d
svd_A$v

[,1]       [,2]       [,3]        [,4]      
[1,] -0.2816569  0.7303849 -0.42412326  0.4553316
[2,] -0.5912537  0.1463017 -0.18371213 -0.7715340
[3,]  0.2247823 -0.4040717 -0.88586638 -0.0379443
[4,] -0.7214994 -0.5309048  0.04012567  0.4426835

[1] 13.161210  6.999892  3.432793

[,1]       [,2]        [,3]      
[1,] -0.8557101  0.01464091 -0.5172483
[2,]  0.1555269 -0.94610374 -0.2840759
[3,] -0.4935297 -0.32353262  0.8073135

Relación entre $u_i$ y $v_i$

In [18]:
thinSVD_A$u
ui_fun <- function(i) A %*% svd_A$v[,i] / svd_A$d[i]
sapply(1:ranA, ui_fun)

[,1]       [,2]       [,3]       
[1,] -0.2816569  0.7303849 -0.42412326
[2,] -0.5912537  0.1463017 -0.18371213
[3,]  0.2247823 -0.4040717 -0.88586638
[4,] -0.7214994 -0.5309048  0.04012567

[,1]       [,2]       [,3]       
[1,] -0.2816569  0.7303849 -0.42412326
[2,] -0.5912537  0.1463017 -0.18371213
[3,]  0.2247823 -0.4040717 -0.88586638
[4,] -0.7214994 -0.5309048  0.04012567

In [19]:
thinSVD_A$v
vi_fun <- function(i) t(A) %*% svd_A$u[,i] / svd_A$d[i]
sapply(1:ranA, vi_fun)

[,1]       [,2]        [,3]      
[1,] -0.8557101  0.01464091 -0.5172483
[2,]  0.1555269 -0.94610374 -0.2840759
[3,] -0.4935297 -0.32353262  0.8073135

[,1]       [,2]        [,3]      
[1,] -0.8557101  0.01464091 -0.5172483
[2,]  0.1555269 -0.94610374 -0.2840759
[3,] -0.4935297 -0.32353262  0.8073135